'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GlobalStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PTFTP.GlobalStrings", GetType(GlobalStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property apply() As String
            Get
                Return ResourceManager.GetString("apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete?.
        '''</summary>
        Friend Shared ReadOnly Property ask_should_delete() As String
            Get
                Return ResourceManager.GetString("ask_should_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelled.
        '''</summary>
        Friend Shared ReadOnly Property cancelled() As String
            Get
                Return ResourceManager.GetString("cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes will take effect after restart.
        '''</summary>
        Friend Shared ReadOnly Property changes_after_reset() As String
            Get
                Return ResourceManager.GetString("changes_after_reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection limit.
        '''</summary>
        Friend Shared ReadOnly Property conn_limit() As String
            Get
                Return ResourceManager.GetString("conn_limit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect.
        '''</summary>
        Friend Shared ReadOnly Property connect() As String
            Get
                Return ResourceManager.GetString("connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copyright.
        '''</summary>
        Friend Shared ReadOnly Property copyright() As String
            Get
                Return ResourceManager.GetString("copyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property delete() As String
            Get
                Return ResourceManager.GetString("delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property download() As String
            Get
                Return ResourceManager.GetString("download", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property edit() As String
            Get
                Return ResourceManager.GetString("edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edited.
        '''</summary>
        Friend Shared ReadOnly Property edited() As String
            Get
                Return ResourceManager.GetString("edited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad operation !!!.
        '''</summary>
        Friend Shared ReadOnly Property err_bad_op() As String
            Get
                Return ResourceManager.GetString("err_bad_op", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad queue size!.
        '''</summary>
        Friend Shared ReadOnly Property err_bad_queue_count() As String
            Get
                Return ResourceManager.GetString("err_bad_queue_count", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to connect!.
        '''</summary>
        Friend Shared ReadOnly Property err_cant_connect() As String
            Get
                Return ResourceManager.GetString("err_cant_connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to delete!.
        '''</summary>
        Friend Shared ReadOnly Property err_cant_delete() As String
            Get
                Return ResourceManager.GetString("err_cant_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t load!.
        '''</summary>
        Friend Shared ReadOnly Property err_cant_load() As String
            Get
                Return ResourceManager.GetString("err_cant_load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t save!.
        '''</summary>
        Friend Shared ReadOnly Property err_cant_save() As String
            Get
                Return ResourceManager.GetString("err_cant_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sorry, file is used right now. Please try again in a few seconds..
        '''</summary>
        Friend Shared ReadOnly Property err_file_in_use() As String
            Get
                Return ResourceManager.GetString("err_file_in_use", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property exitText() As String
            Get
                Return ResourceManager.GetString("exitText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Friend Shared ReadOnly Property file() As String
            Get
                Return ResourceManager.GetString("file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished.
        '''</summary>
        Friend Shared ReadOnly Property finished() As String
            Get
                Return ResourceManager.GetString("finished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property help() As String
            Get
                Return ResourceManager.GetString("help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Host.
        '''</summary>
        Friend Shared ReadOnly Property host() As String
            Get
                Return ResourceManager.GetString("host", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icons.
        '''</summary>
        Friend Shared ReadOnly Property icons() As String
            Get
                Return ResourceManager.GetString("icons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid operation.
        '''</summary>
        Friend Shared ReadOnly Property invalid_op() As String
            Get
                Return ResourceManager.GetString("invalid_op", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property language() As String
            Get
                Return ResourceManager.GetString("language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List.
        '''</summary>
        Friend Shared ReadOnly Property list() As String
            Get
                Return ResourceManager.GetString("list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property login() As String
            Get
                Return ResourceManager.GetString("login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Move.
        '''</summary>
        Friend Shared ReadOnly Property move() As String
            Get
                Return ResourceManager.GetString("move", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New folder.
        '''</summary>
        Friend Shared ReadOnly Property new_folder() As String
            Get
                Return ResourceManager.GetString("new_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operation Queue.
        '''</summary>
        Friend Shared ReadOnly Property op_queue() As String
            Get
                Return ResourceManager.GetString("op_queue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port.
        '''</summary>
        Friend Shared ReadOnly Property port() As String
            Get
                Return ResourceManager.GetString("port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferences.
        '''</summary>
        Friend Shared ReadOnly Property preferences() As String
            Get
                Return ResourceManager.GetString("preferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property refresh() As String
            Get
                Return ResourceManager.GetString("refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rename.
        '''</summary>
        Friend Shared ReadOnly Property rename() As String
            Get
                Return ResourceManager.GetString("rename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rename.
        '''</summary>
        Friend Shared ReadOnly Property renameAction() As String
            Get
                Return ResourceManager.GetString("renameAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property save() As String
            Get
                Return ResourceManager.GetString("save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size.
        '''</summary>
        Friend Shared ReadOnly Property size() As String
            Get
                Return ResourceManager.GetString("size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speed.
        '''</summary>
        Friend Shared ReadOnly Property speed() As String
            Get
                Return ResourceManager.GetString("speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unlimited.
        '''</summary>
        Friend Shared ReadOnly Property unlimited() As String
            Get
                Return ResourceManager.GetString("unlimited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload.
        '''</summary>
        Friend Shared ReadOnly Property upload() As String
            Get
                Return ResourceManager.GetString("upload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Friend Shared ReadOnly Property username() As String
            Get
                Return ResourceManager.GetString("username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend Shared ReadOnly Property version() As String
            Get
                Return ResourceManager.GetString("version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View.
        '''</summary>
        Friend Shared ReadOnly Property view() As String
            Get
                Return ResourceManager.GetString("view", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Official website.
        '''</summary>
        Friend Shared ReadOnly Property webLink() As String
            Get
                Return ResourceManager.GetString("webLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Website.
        '''</summary>
        Friend Shared ReadOnly Property website() As String
            Get
                Return ResourceManager.GetString("website", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
